twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        paprec_back_office_url: "%env(PAPREC_BACK_OFFICE_URL)%"
        paprec_public_technical_service: "%env(PAPREC_PUBLIC_TECHNICAL_SERVICE)%"
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
        google_places_secret_key: '%env(GOOGLE_PLACES_SECRET_KEY)%'
        google_tag_manager: '%env(GOOGLE_TAG_MANAGER)%'
