<?php

namespace App\Repository;

/**
 * FollowUpFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowUpFileRepository extends \Doctrine\ORM\EntityRepository
{
}
