<?php

namespace App\Repository;

/**
 * MissionSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionSheetLineRepository extends \Doctrine\ORM\EntityRepository
{
}
