<?php

namespace App\Repository;

/**
 * OtherNeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherNeedRepository extends \Doctrine\ORM\EntityRepository
{
}
