<?php

namespace App\Repository;

/**
 * RangeLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangeLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
