# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    paprec.timezone.default: 'Europe/Paris'
    paprec_languages:
        - FR

    paprec_types_picture:
        - PICTO
        - PICTURE
        - PILOTPICTURE

    paprec_other_need_types_picture:
        - PICTURE

    paprec_custom_area_types_picture:
        - LEFT
        - RIGHT

    paprec_custom_area_codes:
        - catalog_top
        - catalog_first_block
        - catalog_second_block
        - catalog_third_block

    paprec.product.picto_path: "%kernel.project_dir%/public/uploads/pictos"
    paprec.range.picto_path: "%kernel.project_dir%/public/uploads/pictos"
    paprec.agency.picto_path: "%kernel.project_dir%/public/uploads/pictos"
    paprec.other_need.picto_path: "%kernel.project_dir%/public/uploads/pictos"
    paprec.custom_area.picto_path: "%kernel.project_dir%/public/uploads/pictos"
    paprec.php_path: "%env(PAPREC_PHP_PATH)%"
    paprec.project_path: "%env(PAPREC_PROJECT_PATH)%"

    paprec.product.catalog:
        - REGULAR
        - PONCTUAL
        - MATERIAL

    paprec_transport_types:
        - CBR_REG
        - CBR_PONCT
        - VL_PL_CFS_REG
        - VL_PL_CFS_PONCT
        - VL_PL
        - BOM
        - PL_PONCT

    paprec.data_tmp_directory: "%kernel.project_dir%/data/tmp"
    paprec.files_directory: "%kernel.project_dir%/data/pdf"
    paprec.file_names:
        - cg
    paprec.cover_file_names:
        - cover

    paprec_quote_status:
        - QUOTE_CREATED
        - QUOTE_SENT
        - CONTRACT_SENT
        - CONTRACT_SIGNED
        - CONTRACT_LOST

    paprec_quote_access:
        - STAIRS
        - ELEVATOR
        - GROUND

    paprec_quote_catalog:
        - REGULAR
        - PONCTUAL
        - MATERIAL

    paprec_agency_template:
        - LCB
        - CFS
        - LPP
        - IDF
        - IN_SITU

    paprec_quote_access_price:
        STAIRS: 20
        ELEVATOR: 10
        GROUND: 0

    tmp_lock_prog: 20

    paprec_quote_staff:
        - '150'
        - '51100'
        - '101250'
        - '251500'
        - '500+'

    paprec_quote_floor_number:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9

    paprec.frequency_interval.monthly_coefficients:
        week: 4.33
        month: 1.08
        bimestre: 0.54
        quarter: 0.36

    paprec.follow_up.status:
        - PENDING
        - CLOSED

    paprec.product.calculation_formula:
        - REGULAR
        - PACKAGE
        - UNIT_PRICE

    paprec.setting.keys:
        - FOLLOW_UP_RELAUNCHED_DAYS
        - DASHBOARD_FOLLOW_UP_FILTER_PRICE
        - PRODUCT_MERCURIAL

    paprec.setting.max_by_key:
        FOLLOW_UP_RELAUNCHED_DAYS: 1
        DASHBOARD_FOLLOW_UP_FILTER_PRICE: -1
        PRODUCT_MERCURIAL: -1

    paprec.quote_request_file.directory: "%kernel.project_dir%/data/quote-request/file"
    paprec.quote_request_file.max_file_size: 100000000
    paprec.follow_up_file.directory: "%kernel.project_dir%/data/follow-up/file"
    paprec.follow_up_file.max_file_size: 100000000
    paprec.agency_file.directory: "%kernel.project_dir%/data/agency/file"
    paprec.agency_file.max_file_size: 100000000

    paprec.interest_default_email:
        GRANDS_ENSEMBLES: '%env(PAPREC_INTEREST_DEFAULT_EMAIL_GRANDS_ENSEMBLES)%'
        RESEAUX_AGENCES: '%env(PAPREC_INTEREST_DEFAULT_EMAIL_RESEAUX_AGENCES)%'
        DESTRUCTION_SECURISEE: '%env(PAPREC_INTEREST_DEFAULT_EMAIL_DESTRUCTION_SECURISEE)%'
        AUDIT_CARACTERISATION: '%env(PAPREC_INTEREST_DEFAULT_EMAIL_AUDIT_CARACTERISATION)%'
        COLLECTE_IMMEUBLE: '%env(PAPREC_INTEREST_DEFAULT_EMAIL_COLLECTE_IMMEUBLE)%'
        ANIMATION_SENSIBILISATION: '%env(PAPREC_INTEREST_DEFAULT_EMAIL_ANIMATION_SENSIBILISATION)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.intl-extra:
        class: Twig\Extra\Intl\IntlExtension
        tags:
            - { name: twig.extension }

